package com.kernelcraft.core.security.governance

import android.content.Context
import android.os.Build
import android.util.Base64
import com.kernelcraft.core.security.crypto.KeyStoreManager
import com.kernelcraft.core.security.runtime.RuntimeSecurityPolicy
import com.kernelcraft.core.security.storage.EphemeralStorageManager
import org.json.JSONObject
import java.security.KeyFactory
import java.security.PublicKey
import java.security.Signature
import java.security.spec.X509EncodedKeySpec

/**
 * Result of the remote security governance attestation check.
 */
data class GovernanceVerdict(
    val isPermittedToExecute: Boolean,
    val isEmergencyHaltActive: Boolean,
    val isDecoyModeRecommended: Boolean,
    val haltReason: String? = null,
    val minSupportedVersion: Int = 1,
    val payloadTimestamp: Long = 0L
)

/**
 * Manages zero-trust remote governance, cryptographically signed kill-switches,
 * and emergency revocation attestation.
 */
object SecurityGovernanceManager {

    // Baked-in Offline Emergency Governance Root Public Key (ECDSA P-256 / X.509 SubjectPublicKeyInfo)
    // In production, the private key is held offline in an air-gapped HSM.
    private const val GOVERNANCE_ROOT_PUBLIC_KEY_BASE64 =
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE23qE0rO+698Z8HkXf6jWf3QZ5fW2xLgP1d" +
        "2pS6jM4GkR1n+6Mh9vG2e9d7x1y8gB1vO+2lF9pA6d2kL3pX4A==" // 65-byte uncompressed EC P-256 point

    @Volatile
    private var lastVerdict: GovernanceVerdict = GovernanceVerdict(
        isPermittedToExecute = true,
        isEmergencyHaltActive = false,
        isDecoyModeRecommended = false
    )

    /**
     * Parses and cryptographically validates an ephemeral remote governance payload.
     *
     * @param rawJsonPayload The raw JSON string containing governance rules.
     * @param detachedSignatureBase64 The base64-encoded ECDSA P-256 signature generated by the offline governance root key.
     * @param currentVersionCode The version code of the running application.
     */
    fun processGovernancePayload(
        context: Context? = null,
        rawJsonPayload: String,
        detachedSignatureBase64: String,
        currentVersionCode: Int = 1,
        bypassSignatureVerificationForTesting: Boolean = false
    ): GovernanceVerdict {
        // 1. Asymmetric Signature Verification: Reject unauthenticated or tampered payloads
        if (!bypassSignatureVerificationForTesting) {
            val isAuthentic = verifySignature(rawJsonPayload, detachedSignatureBase64)
            if (!isAuthentic) {
                return GovernanceVerdict(
                    isPermittedToExecute = false,
                    isEmergencyHaltActive = true,
                    isDecoyModeRecommended = false,
                    haltReason = "Cryptographic signature verification failed on remote governance payload."
                )
            }
        }

        // 2. Parse authenticated governance rules
        try {
            val json = JSONObject(rawJsonPayload)
            val status = json.optString("revocation_status", "ACTIVE")
            val emergencyKill = json.optBoolean("emergency_kill_active", false)
            val minVersion = json.optInt("min_supported_version_code", 1)
            val decoyActive = json.optBoolean("decoy_mode_active", false)
            val timestamp = json.optLong("timestamp", 0L)

            val isRevoked = (status.equals("REVOKED", ignoreCase = true) || emergencyKill)
            val isVersionOutdated = currentVersionCode < minVersion

            val isHalted = isRevoked || isVersionOutdated
            val haltReason = when {
                isRevoked -> "Emergency Security Kill-Switch: This application build has been revoked by security operations."
                isVersionOutdated -> "Critical Security Update Required: Installed version $currentVersionCode is deprecated (minimum required: $minVersion)."
                else -> null
            }

            // 3. Fail-Secure Enforcement: Purge keys and data if revoked
            if (isHalted) {
                executeEmergencyZeroization(context)
            }

            // 4. Update dynamic pinsets if included in payload
            if (json.has("pinset_update")) {
                val pinsArray = json.getJSONArray("pinset_update")
                val newPins = mutableListOf<String>()
                for (i in 0 until pinsArray.length()) {
                    newPins.add(pinsArray.getString(i))
                }
                DynamicPinningManager.updateActivePins(newPins)
            }

            // 5. Update Decoy Mode
            if (decoyActive) {
                DecoyModeManager.setDecoyMode(true)
            }

            val verdict = GovernanceVerdict(
                isPermittedToExecute = !isHalted,
                isEmergencyHaltActive = isHalted,
                isDecoyModeRecommended = decoyActive,
                haltReason = haltReason,
                minSupportedVersion = minVersion,
                payloadTimestamp = timestamp
            )
            lastVerdict = verdict
            return verdict
        } catch (e: Exception) {
            return GovernanceVerdict(
                isPermittedToExecute = false,
                isEmergencyHaltActive = true,
                isDecoyModeRecommended = false,
                haltReason = "Malformed governance payload: ${e.message}"
            )
        }
    }

    /**
     * Verifies detached ECDSA P-256 signature using the embedded governance public key.
     */
    fun verifySignature(data: String, signatureBase64: String): Boolean {
        return try {
            val keyBytes = decodeBase64(GOVERNANCE_ROOT_PUBLIC_KEY_BASE64)
            val spec = X509EncodedKeySpec(keyBytes)
            val keyFactory = KeyFactory.getInstance("EC")
            val publicKey: PublicKey = keyFactory.generatePublic(spec)

            val signature = Signature.getInstance("SHA256withECDSA")
            signature.initVerify(publicKey)
            signature.update(data.toByteArray(Charsets.UTF_8))

            val sigBytes = decodeBase64(signatureBase64)
            signature.verify(sigBytes)
        } catch (_: Exception) {
            false
        }
    }

    private fun decodeBase64(base64Str: String): ByteArray {
        return try {
            Base64.decode(base64Str, Base64.DEFAULT)
        } catch (_: Throwable) {
            java.util.Base64.getDecoder().decode(base64Str)
        }
    }

    /**
     * Executes immediate in-memory and storage zeroization upon confirmed kill-switch trigger.
     */
    fun executeEmergencyZeroization(context: Context? = null) {
        // Scrub Keystore-backed secrets and memory
        RuntimeSecurityPolicy.scrubMemory()
        context?.let { EphemeralStorageManager.cleanEphemeralCache(it) }
    }

    fun getLastVerdict(): GovernanceVerdict = lastVerdict
}
